config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new]
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]
  root to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, :moderator, presence: true
  #todo write moderator method
  belongs_to :moderator,
    class_name: :User

  has_many :posts,
    through: :post_subs,
    source: :post

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"><%= @sub.description %></textarea>
  </label>

  <input type="submit">

</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |subreddit| %>
    <li>
    <%= link_to subreddit.title, sub_url(subreddit), method: :get %>
    </li>
  <% end %>
</ul>

<%= button_to "New Sub", new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h1>Create a Sub</h1>

<form action="<%= subs_url %>" method="post">
<%= auth_token %>

<label>
  Title
  <br>
  <input type="text" name="sub[title]">
</label>

<br>
<label>
  Description
  <br>
<textarea name="sub[description]" rows="8" cols="80"></textarea>
</label>
<br>

<input type="submit">
</form>

app/views/subs/show.html.erb
<h1>Now Viewing: <u><%= @sub.title %></u></h1>

<h3>Description</h3>
<%= @sub.description %>

<ul>
<% @sub.posts.each do |post| %>
  <li> <%= link_to post.title, post_url(post), method: :get %></li>
<% end %>
</ul>

<br><br>
<%= button_to "Add Post", new_sub_post_url(@sub), method: :get %>

<br><br>
<%= link_to "Edit This Sub", edit_sub_url(@sub), method: :get %>