config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new]
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]
  root to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  # validates :author, :title, presence: true

  #todo write author method

  belongs_to :author,
    class_name: :User

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_user_match, only: [:edit, :update, :destroy]
  def new
    @post = Post.new
    render :new
  end

  def create
    # @subs = Sub.all
    @post_params = post_params
    subs = @post_params.delete(:sub_ids).map(&:to_i)
    @post = Post.new(@post_params)
    @post.author_id = current_user.id
    if @post.save
      subs.each do |sub_id|
        PostSub.create!(sub_id: sub_id, post_id: @post.id)
      end
      redirect_to post_url(@post)
    else

      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post_params = post_params
    subs = @post_params.delete(:sub_ids).map(&:to_i)
    if @post.update(@post_params)
      PostSub.where(post_id: @post.id).destroy_all
      subs.each do |sub_id|
        PostSub.create!(sub_id: sub_id, post_id: @post.id)
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    sub_id = @post.sub_id
    @post.delete
    redirect_to sub_url(sub_id)
  end

  def show
    @post = Post.find(params[:id])
  end

  def require_user_match
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless @post.author_id == current_user.id
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit A Post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>
    Title
    <br>
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br><br>

  <label>
    URL
    <br>
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br><br>

  <label>
    Content
    <br>
    <textarea name="post[content]" rows="8" cols="80"> <%= @post.content %></textarea>
  </label>

  <br><br>
  <% Sub.all.each do |subr| %>
    <label><%= subr.title %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= subr.id %>">
    </label>
  <% end %>
  <br><br>

  <input type="submit">
</form>

app/views/posts/new.html.erb
<h1>Create A Post</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <label>
    Title
    <br>
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br><br>

  <label>
    URL
    <br>
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br><br>

  <label>
    Content
    <br>
    <textarea name="post[content]" rows="8" cols="80"> <%= @post.content %></textarea>
  </label>

  <br><br>
  <% Sub.all.each do |subr| %>
    <label><%= subr.title %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= subr.id %>">
    </label>
  <% end %>
  <br>
  <input type="submit">
</form>

app/views/posts/show.html.erb
<h3> <%= link_to @post.title, post_url(@post), method: :get %> </h3>
<h3>Content</h3>
<%= @post.content %>
<h3>Comments</h3>
<ul>
<% @post.comments.each do |comment| %>
  <li><%= comment.content %></li>
<% end %>
</ul>
<br><br>
<%= link_to "Edit Post", edit_post_url(@post), method: :get %>
<%= link_to "Delete Post", post_url(@post), method: :delete %>
<%= link_to "Add Comment", new_post_comment_url(@post), method: :get %>